# hosts.yml
all:
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_ansible"
    ansible_become: true
  children:
    control:
      hosts:
        localhost:
          ansible_connection: local
          # ansible_python_interpreter: "{{ lookup('env', 'HOME') }}/miniconda3/envs/ans118/bin/python" 
          ansible_python_interpreter: /usr/bin/python3
    bioinfo:
      hosts:
        box-01:
          ansible_host: "192.168.1.3"

    ubuntu_all:
      hosts:
        srv-01:
          ansible_host: "10.0.0.11"
        srv-02:
          ansible_host: "10.0.0.12"
        laptop-01:
          ansible_host: "192.168.1.50"
    edge:
      hosts:
        srv-02: {}
